### ISSUE TITLE
Apply the projection parameters on the coordinates.

### ISSUE THREAD

**Issue by mlentwicklung** [elda27/pydrr#3]
Hi all,

How could we apply a projection parameters on a point (x,y,z) and calculate the resulting coordinates (x*,y*) in the projected image?

**Comment by elda27** [comment]
Second argument of Projector.project:
https://github.com/elda27/pydrr/blob/4bf56a760f760066a051fa2e5306e09e2b4b3f1a/pydrr/Projector.py#L18

This is GeometryContext instance.
https://github.com/elda27/pydrr/blob/master/pydrr/GeometryContext.py

If you have already computed intrinsic and extrinsic matrix, you set GeometryContext.intrinsic  and extrinsic.
Or you set each parameters such as pixel size.
