### ISSUE TITLE
DRR generation

### ISSUE THREAD

**Issue by SXX1015** [elda27/pydrr#4]
hi,all
   Is the drr.mhd file generated in the source code a three-dimensional image of drr? Is there three? How can I directly generate a projected DRR image?
   Look forward to your answer！

**Comment by elda27** [comment]
Please share the source code because I don't know your situation. 

There are my guess.
If you use mhd module to import volume file, the image has x, y, z components.
Or if you use mhd module to import 2 dimensional image, the image has x, y and channel components.
The channel comonent means usually time or number of volumes to generate drr.
This library support multiple inputs and multiple outputs so output image has chanel component.

**Comment by SXX1015** [comment]
This is my input,I converted my CT data into MHD file as input.
`def main():  
    # if len(sys.argv) < 2: 
    #     print('rendering.py <volume path>')
    #     return
    # mhd_filename = sys.argv[1]
   
    mhd_filename = "./SaveRaw/sample.mhd/"
    # Load materials
    # volume, spacing = load_image(mhd_filename)
    itkimage = sitk.ReadImage(mhd_filename)
    volume = sitk.GetArrayFromImage(itkimage)
    spacing = itkimage.GetSpacing()
    spacing = spacing[::-1]`
According to the source code you shared, I didn’t change the output, it was generated as drr.mhd

` # Device memory -> Host memory   #设备GPU内存）->纹理内存
    image = d_image.get()
    print('Result image shape:', image.shape)  # 1280 1280 3
    plt.figure(figsize=(16,9))
    n_show_channels = 3
    for i in range(min(image.shape[2], n_show_channels)):
        ax = plt.subplot(1, min(image.shape[2], n_show_channels), i+1)
        divider = mpl_toolkits.axes_grid1.make_axes_locatable(ax)   #轴位置
        cax = divider.append_axes('right', '5%', pad='3%')
        im = ax.imshow(image[:, :, i], interpolation='none', cmap='gray')
        plt.colorbar(im, cax=cax)
    plt.show()

    save_image('drr.mhd', image, image_spacing)`
I just want to get a two-dimensional graph with the result drr, such as drr.png, but the generated drr.mhd file is (1280,1280,3), I don’t understand what this 3 represents, it is a three-dimensional drr Image? Or are three two-dimensional drr images generated? Maybe you can share with me the code to generate the png image. I will be very grateful！

**Comment by elda27** [comment]
I forget implementation detail but I remember it to see your sample code.

I understand your example is a part of the my example source.

The channel component has the number of transform matrix too.
The transformation matrix consists from camera matrix (view matrix) and pose matrix (usually this is only called transform matrix).
In your sample code will generate three posture (axial, supine and coronal axes) images.
So the channel component has three images.

You should see this line in my example code.
https://github.com/elda27/pydrr/blob/4bf56a760f760066a051fa2e5306e09e2b4b3f1a/examples/rendering.py#L98
