### ISSUE TITLE
pycuda.driver.CompileError // nvcc fatal :

### ISSUE THREAD

**Issue by ryukyungjoon** [elda27/pydrr#6]
pycuda.driver.CompileError:
command: nvcc --cubin --ptxas-options=-v -arch sm_61 -m64 ...
stdout:
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH

how to fix this error?

[current specs]
anaconda envs : python 3.7 / cuda 9.0
python IDE : pycharm community

please answer me.
thank you.

**Comment by elda27** [comment]
Please add path of the cl.exe a.k.a msvc compiler to your PATH.
nvcc depends on c++ compiler on any OS.
