### ISSUE TITLE
How to generate DRR?

### ISSUE THREAD

**Issue by ryukyungjoon** [elda27/pydrr#7]
How to generate DRR using rendering.py? 

I want a DRR image that projects 200 CT (Dicom) images.

ex) CLI - python rendering.py /img/CT_images_001.dcm /img/CT_images_002.dcm ... /img/CT_images_200.dcm

can i get the DRR of 200 CT images?

please answer me.

if your answer is no, where should i fix it?

**Comment by elda27** [comment]
No, you cannot generate DRR images directly from dicom.
You must convert the mhd image before running this script.

You can use vtk or itk to convert the file format.
There is also a manual conversion that can be easily done with a 3D slicer.

**Comment by ryukyungjoon** [comment]
Thank you answer for me.

can i ask you question one more?

Isn't load_image() a function that converts dicom to mhd?

if your answer is no, how to convert dicom to mhd in python?

or give me a example script 
what is a volume path? what is a volume? in this script 'rendering.py <volume path>'

**Comment by elda27** [comment]
Which line do you mean?

Probably `load_volume` function is supported to load dicom volume.
I forget the detail implementation of ITK.
https://github.com/elda27/pydrr/blob/4bf56a760f760066a051fa2e5306e09e2b4b3f1a/pydrr/utils.py#L25

You can find it on stackoverflow or something else.
https://stackoverflow.com/questions/48185544/read-and-open-dicom-images-using-python

```python
ds = dicom.dcmread(image_path)
ds.pixel_array # It's a 2D image but you can retrieve 3d array stacking it.
```
